/**
 * Run one full round of AI Catan (all players take one turn).
 * Usage:  npx ts-node run-turn.ts <seed>
 *
 * Loads:  games/<seed>/state.json  (or state-after-turn-NN.json)
 * Saves:  games/<seed>/turn-NN/dialogue.html
 *         games/<seed>/turn-NN/map.html
 *         games/<seed>/state-after-turn-NN.json
 */
import * as dotenv from 'dotenv';
dotenv.config();

import * as fs from 'fs';
import * as path from 'path';
import { deserializeState, serializeState } from './src/state-serializer';
import { createAgent } from './src/agents/agent';
import { runMainTurn } from './src/simulator';
import { calculateVP, calculateVisibleVP, checkWin } from './src/gameState';
import { TurnEntry, TurnLog, TurnSummary, GameState } from './src/types';

// ─── CSS colors (must match run-setup.ts) ────────────────────────────────────

const CSS_COLORS: Record<string, string> = {
  chatgpt:  '#A73E3A',
  gemini:   '#2863B8',
  grok:     '#2C2C2E',
  deepseek: '#3EABAB',
  claude:   '#409128',
  kimi:     '#9F43A8',
  lama:     '#989131',
};

/** Derive brand hex from model name, falling back to stored color key, then grey. */
function modelToHex(model: string): string {
  if (model.startsWith('gpt') || model.startsWith('o1') || model.startsWith('o3')) return CSS_COLORS.chatgpt;
  if (model.startsWith('gemini'))    return CSS_COLORS.gemini;
  if (model.startsWith('grok'))      return CSS_COLORS.grok;
  if (model.startsWith('deepseek'))  return CSS_COLORS.deepseek;
  if (model.startsWith('claude'))    return CSS_COLORS.claude;
  if (model.startsWith('kimi'))      return CSS_COLORS.kimi;
  if (model.startsWith('llama') || model.startsWith('lama')) return CSS_COLORS.lama;
  return '#888888';
}

function playerHex(model: string, colorKey: string): string {
  return CSS_COLORS[colorKey] ?? modelToHex(model);
}

const PORT_DEFS = [
  { q: -1, r: -1, seaDir: 3, type: 'sheep' },
  { q:  0, r: -2, seaDir: 2, type: 'any'   },
  { q:  1, r: -2, seaDir: 1, type: 'ore'   },
  { q:  2, r: -2, seaDir: 0, type: 'any'   },
  { q:  2, r:  0, seaDir: 1, type: 'wheat' },
  { q:  1, r:  1, seaDir: 5, type: 'any'   },
  { q:  0, r:  2, seaDir: 4, type: 'brick' },
  { q: -2, r:  2, seaDir: 4, type: 'any'   },
  { q: -2, r:  0, seaDir: 3, type: 'wood'  },
];

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const seed = process.argv[2] ? parseInt(process.argv[2]) : null;
  if (!seed) { console.error('Usage: npx ts-node run-turn.ts <seed>'); process.exit(1); }

  const gameDir = path.join('games', String(seed));

  // Find the most recent state file — prefer state-after-turn-NN.json (highest NN), fall back to state.json
  const allFiles = fs.readdirSync(gameDir).filter(f => f.endsWith('.json'));
  const turnFiles = allFiles
    .map(f => ({ f, n: Number(f.match(/state-after-turn-(\d+)\.json/)?.[1] ?? -1) }))
    .filter(x => x.n >= 0)
    .sort((a, b) => b.n - a.n);
  const stateFile = turnFiles.length > 0 ? turnFiles[0].f : 'state.json';
  const statePath = path.join(gameDir, stateFile);

  console.log(`\nLoading: ${statePath}`);
  const raw = JSON.parse(fs.readFileSync(statePath, 'utf-8'));
  const state = deserializeState(raw);

  const turnNum = state.turn;
  const turnLabel = String(turnNum).padStart(2, '0');
  const turnDir = path.join(gameDir, `turn-${turnLabel}`);
  fs.mkdirSync(turnDir, { recursive: true });

  console.log(`Running turn ${turnNum} (${state.players.length} players)...\n`);

  // Load reflections file if present (generated by reflect.ts after prior turns)
  const reflections = new Map<string, string>();
  const reflDir = path.join(gameDir, 'reflections');
  if (fs.existsSync(reflDir)) {
    const reflFiles = fs.readdirSync(reflDir)
      .filter(f => f.match(/^after-turn-\d+\.md$/))
      .sort((a, b) => {
        const na = parseInt(a.match(/(\d+)/)![1]);
        const nb = parseInt(b.match(/(\d+)/)![1]);
        return nb - na;
      });
    if (reflFiles.length > 0) {
      const reflContent = fs.readFileSync(path.join(reflDir, reflFiles[0]), 'utf-8');
      // Parse each player's reflection block: "## Name — N VP" followed by text until next "##"
      const blocks = reflContent.split(/^## /m).slice(1);
      for (const block of blocks) {
        const nameMatch = block.match(/^(.+?) —/);
        if (!nameMatch) continue;
        const name = nameMatch[1].trim();
        const player = state.players.find(p => p.name === name);
        if (!player) continue;
        const text = block.replace(/^.+\n\n/, '').trim();
        reflections.set(player.id, text);
        console.log(`  Loaded reflection for ${name}`);
      }
    }
  }

  // Build agent map from player state (model stored on each player)
  const agentMap = new Map(
    state.players.map(p => [p.id, createAgent(p.id, p.name, p.model, reflections.get(p.id))])
  );

  // Shared round log — grows as each player acts; later players see full prior context
  const roundLog: TurnLog = [];

  // ── Run all players ─────────────────────────────────────────────────────────
  for (let i = 0; i < state.players.length; i++) {
    state.currentPlayerIndex = i;
    const player = state.players[i];
    const vp = calculateVP(state, player.id);

    console.log(`\n${'─'.repeat(50)}`);
    console.log(`${player.name} — ${vp} VP`);
    console.log('─'.repeat(50));

    // Insert a turn-start marker with full player state snapshot
    // Dev cards are hidden for non-active players to prevent information leaks
    const playerSnapshot = state.players.map(p => {
      const isActive = p.id === player.id;
      return {
        name: p.name,
        model: p.model,
        color: p.color,
        vp: isActive ? calculateVP(state, p.id) : calculateVisibleVP(state, p.id),
        resources: { ...p.resources },
        devCards: isActive ? [...p.devCards] : [],
        devCardCount: p.devCards.length,
      };
    });
    roundLog.push({
      phase: 'system',
      fromName: 'Game',
      fromId: null,
      publicMessage: `=== ${player.name}'s turn (turn ${turnNum}) — ${vp} VP ===`,
      data: { playerSnapshot },
    });

    await runMainTurn(state, agentMap, roundLog);

    // Check win after each player
    const winner = checkWin(state);
    if (winner) {
      state.winner = winner;
      state.phase = 'ended';
      const wp = state.players.find(p => p.id === winner)!;
      console.log(`\n★ ${wp.name} WINS with ${calculateVP(state, winner)} VP!`);
      break;
    }
  }

  // ── Build turn summary from roundLog and push to state ──────────────────────
  state.turnSummaries.push(buildTurnSummary(turnNum, roundLog, state));
  if (state.turnSummaries.length > 10) state.turnSummaries.shift(); // keep rolling window

  // Advance turn counter for next round
  if (state.phase !== 'ended') {
    state.turn++;
  }

  // ── Collect board state for map ─────────────────────────────────────────────
  const hexes = [...state.hexes.values()].map(h => ({
    id: h.id, q: h.q, r: h.r, type: h.type, number: h.number, hasRobber: h.hasRobber,
  }));
  const buildings = [...state.vertices.values()].filter(v => v.building).map(v => {
    const p = state.players.find(pl => pl.id === v.building!.playerId)!;
    return { vertexId: v.id, playerId: p.id, playerName: p.name, playerColor: playerHex(p.model, p.color), buildingType: v.building!.type };
  });
  const roads = [...state.edges.values()].filter(e => e.road).map(e => {
    const p = state.players.find(pl => pl.id === e.road)!;
    return { edgeId: e.id, playerId: p.id, playerName: p.name, playerColor: playerHex(p.model, p.color) };
  });
  const robberHex = [...state.hexes.values()].find(h => h.hasRobber);

  // Final VP for all players
  const scores = state.players.map(p => ({ ...p, colorHex: playerHex(p.model, p.color), vp: calculateVP(state, p.id) }));

  // ── Save outputs ─────────────────────────────────────────────────────────────
  const mapData = { seed, hexes, ports: PORT_DEFS, buildings, roads, robberHexId: robberHex?.id ?? null };
  fs.writeFileSync(path.join(turnDir, 'map.html'),      buildMapHtml(mapData, turnNum, scores));
  fs.writeFileSync(path.join(turnDir, 'dialogue.html'), buildDialogueHtml(seed, turnNum, roundLog, scores));

  const nextStateFile = `state-after-turn-${turnLabel}.json`;
  fs.writeFileSync(path.join(gameDir, nextStateFile), JSON.stringify(serializeState(state), null, 2));

  console.log(`\nSaved to games/${seed}/turn-${turnLabel}/`);
  console.log(`  map.html`);
  console.log(`  dialogue.html`);
  console.log(`  ../${nextStateFile}`);
  console.log(`\nScores after turn ${turnNum}:`);
  for (const p of scores.sort((a, b) => b.vp - a.vp)) {
    console.log(`  ${p.name}: ${p.vp} VP`);
  }
  console.log();
}

main().catch(e => { console.error(e); process.exit(1); });

// ─── Turn summary builder ─────────────────────────────────────────────────────

function buildTurnSummary(turnNum: number, roundLog: TurnLog, state: GameState): TurnSummary {
  const events: string[] = [];

  // Group entries by active player (between system markers)
  let currentPlayer = '';
  const trades: string[] = [];
  const builds: string[] = [];
  const robbers: string[] = [];
  const comments: string[] = [];

  for (const e of roundLog) {
    if (e.phase === 'system') {
      // Flush previous player's events
      if (currentPlayer && (trades.length || builds.length || robbers.length)) {
        const vp = calculateVP(state, state.players.find(p => p.name === currentPlayer)?.id ?? '');
        const parts: string[] = [`${currentPlayer}(${vp}VP)`];
        if (builds.length) parts.push('built: ' + builds.join(', '));
        if (trades.length) parts.push('traded: ' + trades.slice(0, 3).join('; '));
        if (robbers.length) parts.push(robbers[0]);
        events.push('  ' + parts.join(' | '));
      }
      trades.length = 0; builds.length = 0; robbers.length = 0;
      currentPlayer = e.publicMessage.match(/^=== (.+?)'s turn/)?.[1] ?? '';
      continue;
    }

    if (e.phase === 'build' && e.publicMessage && !e.publicMessage.startsWith('has nothing') && !e.publicMessage.startsWith('I ')) {
      // Only capture the actual build action lines (e.g. "builds road at ...", "upgrades to city at ...", "buys a dev card")
      if (e.publicMessage.match(/^(builds|upgrades|buys|bank-trades)/)) {
        const short = e.publicMessage.replace(/ at [^\s]+ .+$/, ' [placed]').replace(/ at [^\s]+$/, ' [placed]');
        builds.push(short);
      }
    }

    if (e.phase === 'trade_resolve' && e.publicMessage.startsWith('✓ TRADE')) {
      // "✓ TRADE: X gives A, receives B from Y"
      const m = e.publicMessage.match(/✓ TRADE[^:]*: (.+?) gives (.+?), receives (.+?) from (.+)/);
      if (m) trades.push(`${m[1]}→${m[4]}: ${m[2]} for ${m[3]}`);
    }

    if (e.phase === 'robber' && e.publicMessage.startsWith('moves robber')) {
      const m = e.publicMessage.match(/moves robber to ([^,]+), steals .+ from (.+)/);
      if (m) robbers.push(`robber→${m[1]}, stole from ${m[2]}`);
      else robbers.push('moved robber');
    }

    if (e.phase === 'commentary' && e.fromName) {
      comments.push(`${e.fromName}: "${e.publicMessage.slice(0, 80)}${e.publicMessage.length > 80 ? '…' : ''}"`);
    }
  }

  // Flush last player
  if (currentPlayer && (trades.length || builds.length || robbers.length)) {
    const vp = calculateVP(state, state.players.find(p => p.name === currentPlayer)?.id ?? '');
    const parts: string[] = [`${currentPlayer}(${vp}VP)`];
    if (builds.length) parts.push('built: ' + builds.join(', '));
    if (trades.length) parts.push('traded: ' + trades.slice(0, 3).join('; '));
    if (robbers.length) parts.push(robbers[0]);
    events.push('  ' + parts.join(' | '));
  }

  // Notable commentary (deduplicated, max 3)
  const seen = new Set<string>();
  const uniqueComments = comments.filter(c => {
    const key = c.slice(0, 40);
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  }).slice(0, 3);
  if (uniqueComments.length) {
    events.push('  Notable: ' + uniqueComments.join(' | '));
  }

  return { turn: turnNum, events };
}

// ─── Shared SVG JS (same geometry as run-setup.ts) ───────────────────────────

const SHARED_SVG_JS = `
const COLORS={wood:'#2e6b30',wheat:'#c8960e',sheep:'#72b85e',brick:'#aa3e22',ore:'#5a6070',desert:'#c4a96a',ocean:'#14467a'};
const BORDER={wood:'#1e4a20',wheat:'#8f6a08',sheep:'#4e8a3e',brick:'#7a2a14',ore:'#3a4050',desert:'#9a7e48'};
const PORT_COLORS={any:'#9b59b6',wood:'#2e8b30',wheat:'#e0b020',sheep:'#5fba4a',brick:'#cc4428',ore:'#7888aa'};
const PIPS={2:1,3:2,4:3,5:4,6:5,8:5,9:4,10:3,11:2,12:1};
const SVG_NS='http://www.w3.org/2000/svg';
function el(t,a={}){const e=document.createElementNS(SVG_NS,t);for(const[k,v]of Object.entries(a))e.setAttribute(k,v);return e;}
function hexCenter(q,r,sz,ox,oy){return{x:ox+sz*Math.sqrt(3)*(q+r/2),y:oy+sz*1.5*r};}
function hexCorners(cx,cy,sz){return Array.from({length:6},(_,i)=>{const a=-Math.PI/6-Math.PI/3*i;return[cx+sz*Math.cos(a),cy+sz*Math.sin(a)];});}
function portFace(q,r,sd,sz,ox,oy){const{x:cx,y:cy}=hexCenter(q,r,sz,ox,oy);const c=hexCorners(cx,cy,sz);const c1=c[(sd-1+6)%6],c2=c[sd];const mx=(c1[0]+c2[0])/2,my=(c1[1]+c2[1])/2;const dx=mx-cx,dy=my-cy,len=Math.sqrt(dx*dx+dy*dy);return{c1,c2,mx,my,nx:dx/len,ny:dy/len,cx,cy};}
function vertexPos(vid,sz,ox,oy){const ids=vid.split('|').map(h=>h.replace(/^~/,''));let sx=0,sy=0;for(const hid of ids){const[q,r]=hid.split(',').map(Number);const c=hexCenter(q,r,sz,ox,oy);sx+=c.x;sy+=c.y;}return{x:sx/ids.length,y:sy/ids.length};}
function edgePts(eid,sz,ox,oy){const[v1,v2]=eid.split('||');return{p1:vertexPos(v1,sz,ox,oy),p2:vertexPos(v2,sz,ox,oy)};}
function drawBoard(svg,D,W,H,sz){
  const ox=W/2,oy=H/2-10;
  svg.setAttribute('viewBox',\`0 0 \${W} \${H}\`);svg.setAttribute('width',W);svg.setAttribute('height',H);
  svg.appendChild(el('rect',{x:0,y:0,width:W,height:H,fill:COLORS.ocean}));
  for(const hex of D.hexes){
    const{x:cx,y:cy}=hexCenter(hex.q,hex.r,sz,ox,oy);
    const corners=hexCorners(cx,cy,sz);
    const pts=corners.map(([x,y])=>\`\${x.toFixed(1)},\${y.toFixed(1)}\`).join(' ');
    svg.appendChild(el('polygon',{points:pts,fill:COLORS[hex.type]??'#888',stroke:BORDER[hex.type]??'#444','stroke-width':'2'}));
    // Robber
    if(hex.hasRobber){
      svg.appendChild(el('circle',{cx,cy,r:14,fill:'rgba(0,0,0,0.55)','stroke-width':'0'}));
      const rt=el('text',{x:cx,y:cy+5,'text-anchor':'middle','font-size':'14',fill:'#fff'});rt.textContent='♟';svg.appendChild(rt);
    }
    if(hex.type==='desert'){
      if(!hex.hasRobber){const t=el('text',{x:cx,y:cy+6,'text-anchor':'middle','font-size':'22',fill:'rgba(0,0,0,0.28)'});t.textContent='♟';svg.appendChild(t);}
      const lb=el('text',{x:cx,y:cy+22,'text-anchor':'middle','font-size':'8',fill:'rgba(0,0,0,0.3)','letter-spacing':'1'});lb.textContent='DESERT';svg.appendChild(lb);
      continue;
    }
    const isRed=hex.number===6||hex.number===8;
    svg.appendChild(el('circle',{cx,cy,r:18,fill:isRed?'#f5ede0':'#f5f0e8',stroke:isRed?'#c44':'#bbb','stroke-width':'1.5'}));
    const nt=el('text',{x:cx,y:cy+5,'text-anchor':'middle','font-size':'16','font-weight':'bold','font-family':'Georgia,serif',fill:isRed?'#c00':'#222'});nt.textContent=hex.number??'';svg.appendChild(nt);
    const pips=PIPS[hex.number]??0,sp=5,tw=(pips-1)*sp;
    for(let p=0;p<pips;p++)svg.appendChild(el('circle',{cx:cx-tw/2+p*sp,cy:cy+13,r:'1.8',fill:isRed?'#c00':'#444'}));
    const rl=el('text',{x:cx,y:cy-24,'text-anchor':'middle','font-size':'8','letter-spacing':'0.5',fill:'rgba(255,255,255,0.65)'});rl.textContent=hex.type.toUpperCase();svg.appendChild(rl);
  }
  for(const port of D.ports){
    const col=PORT_COLORS[port.type]??'#aaa';
    const f=portFace(port.q,port.r,port.seaDir,sz,ox,oy);
    svg.appendChild(el('line',{x1:f.c1[0],y1:f.c1[1],x2:f.c2[0],y2:f.c2[1],stroke:col,'stroke-width':'5','stroke-linecap':'round'}));
    const lx=f.cx+f.nx*(sz*0.87+sz*0.38),ly=f.cy+f.ny*(sz*0.87+sz*0.38);
    const bgW=port.type==='any'?28:52;
    svg.appendChild(el('rect',{x:lx-bgW/2,y:ly-9,width:bgW,height:16,rx:4,fill:col,opacity:'0.92'}));
    const lt=el('text',{x:lx,y:ly+4,'text-anchor':'middle','font-size':'9','font-weight':'bold','font-family':'Georgia,serif',fill:'#fff'});lt.textContent=port.type==='any'?'3:1':\`2:1 \${port.type[0].toUpperCase()}\`;svg.appendChild(lt);
    svg.appendChild(el('line',{x1:(f.c1[0]+f.c2[0])/2,y1:(f.c1[1]+f.c2[1])/2,x2:lx,y2:ly,stroke:col,'stroke-width':'1.5','stroke-dasharray':'3,2',opacity:'0.6'}));
  }
  // Roads
  for(const road of D.roads){
    const col=road.playerColor;
    const{p1,p2}=edgePts(road.edgeId,sz,ox,oy);
    svg.appendChild(el('line',{x1:p1.x,y1:p1.y,x2:p2.x,y2:p2.y,stroke:'rgba(0,0,0,0.35)','stroke-width':'8','stroke-linecap':'round'}));
    svg.appendChild(el('line',{x1:p1.x,y1:p1.y,x2:p2.x,y2:p2.y,stroke:col,'stroke-width':'5','stroke-linecap':'round'}));
  }
  // Buildings (settlements = circle, cities = larger double ring)
  for(const b of D.buildings){
    const{x,y}=vertexPos(b.vertexId,sz,ox,oy);
    const col=b.playerColor;
    if(b.buildingType==='city'){
      svg.appendChild(el('circle',{cx:x,cy:y,r:13,fill:'rgba(0,0,0,0.4)','stroke-width':'0'}));
      svg.appendChild(el('circle',{cx:x,cy:y,r:12,fill:col,stroke:'#fff','stroke-width':'2.5'}));
      svg.appendChild(el('circle',{cx:x,cy:y,r:6,fill:'rgba(255,255,255,0.35)','stroke-width':'0'}));
    } else {
      svg.appendChild(el('circle',{cx:x,cy:y,r:10,fill:'rgba(0,0,0,0.35)','stroke-width':'0'}));
      svg.appendChild(el('circle',{cx:x,cy:y,r:9,fill:col,stroke:'#fff','stroke-width':'2'}));
    }
  }
}`;

// ─── Map HTML ─────────────────────────────────────────────────────────────────

function buildMapHtml(
  data: { seed: number; hexes: any[]; ports: any[]; buildings: any[]; roads: any[]; robberHexId: string | null },
  turnNum: number,
  scores: Array<{ id: string; name: string; color: string; colorHex: string; model: string; vp: number }>,
): string {
  const scoreboard = scores
    .sort((a, b) => b.vp - a.vp)
    .map(p => {
      const col = p.colorHex;
      return `<div class="sc"><div class="sd" style="background:${col}"></div><b>${escHtml(p.name)}</b><span style="color:#f5d78e;margin-left:6px">${p.vp} VP</span></div>`;
    }).join('');

  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>AI Catan — Turn ${turnNum} Map (Seed ${data.seed})</title>
<style>*{box-sizing:border-box;margin:0;padding:0}body{background:#0d2b4a;font-family:'Georgia',serif;color:#f0e6d3;display:flex;flex-direction:column;align-items:center;min-height:100vh}
header{padding:18px 0 4px;font-size:1.4em;letter-spacing:4px;color:#f5d78e;text-transform:uppercase}
#sub{font-size:0.75em;color:#9ab8d8;letter-spacing:2px;margin-bottom:10px}
#board-svg{display:block;max-width:100%}
#scores{display:flex;gap:14px;margin:10px 0 24px;flex-wrap:wrap;justify-content:center}
.sc{background:rgba(255,255,255,0.06);border:1px solid rgba(255,255,255,0.1);border-radius:8px;padding:7px 14px;display:flex;align-items:center;gap:8px;font-size:0.87em}
.sd{width:12px;height:12px;border-radius:50%}</style></head>
<body><header>AI CATAN</header>
<div id="sub">AFTER TURN ${turnNum} — SEED: ${data.seed}</div>
<svg id="board-svg"></svg>
<div id="scores">${scoreboard}</div>
<script>
const D=${JSON.stringify(data)};
${SHARED_SVG_JS}
drawBoard(document.getElementById('board-svg'),D,760,680,62);
</script></body></html>`;
}

// ─── Dialogue HTML ────────────────────────────────────────────────────────────

const PHASE_LABELS: Record<string, string> = {
  pre_roll:       'PRE-ROLL',
  roll:           'ROLL',
  resources:      'RESOURCES',
  robber:         'ROBBER',
  discard:        'DISCARD',
  dev_card:       'DEV CARD',
  trade_offer:    'TRADE OFFER',
  trade_response: 'TRADE',
  trade_resolve:  'TRADE',
  build:          'BUILD',
  commentary:     '💬',
  system:         '',
};

const PHASE_COLORS: Record<string, string> = {
  roll:           '#d4a017',
  resources:      '#38a169',
  trade_offer:    '#9b59b6',
  trade_response: '#9b59b6',
  trade_resolve:  '#9b59b6',
  build:          '#3182ce',
  robber:         '#e53e3e',
  discard:        '#e53e3e',
  dev_card:       '#805ad5',
  pre_roll:       '#718096',
  commentary:     '#b7791f',
  system:         '#2d3748',
};

function buildDialogueHtml(
  seed: number,
  turnNum: number,
  roundLog: TurnEntry[],
  scores: Array<{ id: string; name: string; color: string; colorHex: string; vp: number }>,
): string {
  // Map player name → resolved hex color
  const playerHexMap: Record<string, string> = {};
  for (const s of scores) playerHexMap[s.name] = s.colorHex;

  let html = '';
  for (const entry of roundLog) {
    if (entry.phase === 'system') {
      const snap = (entry.data as any)?.playerSnapshot as Array<{
        name: string; model: string; color: string; vp: number;
        resources: Record<string,number>; devCards: string[]; devCardCount: number;
      }> | undefined;

      let snapHtml = '';
      if (snap) {
        const rows = snap.map(p => {
          const col = playerHexMap[p.name] ?? '#9ab8d8';
          const res = ['wood','brick','wheat','sheep','ore']
            .map(r => `<span style="opacity:0.7;font-size:0.8em">${r[0].toUpperCase()}:</span><b>${p.resources[r]??0}</b>`)
            .join(' ');
          // Show dev card types only for the active player (devCards non-empty); others show count only
          const cards = p.devCards.length
            ? `<span style="margin-left:8px;color:#c6a;font-size:0.8em">[${p.devCards.join(', ')}]</span>`
            : p.devCardCount > 0
              ? `<span style="margin-left:8px;color:#c6a;font-size:0.8em">[${p.devCardCount} dev card(s)]</span>`
              : '';
          return `<div style="display:flex;align-items:center;gap:10px;padding:4px 0;border-bottom:1px solid rgba(255,255,255,0.05)">
            <div style="width:9px;height:9px;border-radius:50%;background:${col};flex-shrink:0"></div>
            <span style="color:${col};font-weight:bold;min-width:80px;font-size:0.85em">${escHtml(p.name)}</span>
            <span style="color:#f5d78e;min-width:40px;font-size:0.85em">${p.vp} VP</span>
            <span style="display:flex;gap:8px;font-family:monospace;font-size:0.82em;color:#e2e8f0">${res}</span>
            ${cards}
          </div>`;
        }).join('');
        snapHtml = `<div style="margin-top:8px;background:rgba(0,0,0,0.25);border-radius:6px;padding:8px 12px">${rows}</div>`;
      }

      html += `<div style="text-align:center;color:#4a7aab;letter-spacing:2px;font-size:0.82em;
        margin:24px 0 6px;border-top:1px solid #1e3a5c;padding-top:16px">${escHtml(entry.publicMessage)}</div>${snapHtml}`;
      html += `<div style="margin-bottom:10px"></div>`;
      continue;
    }

    // Commentary entries get a special callout style
    if (entry.phase === 'commentary') {
      const nameCol = playerHexMap[entry.fromName] ?? '#9ab8d8';
      html += `<div style="background:rgba(183,121,31,0.10);border:1px solid rgba(183,121,31,0.35);
        border-left:4px solid #b7791f;border-radius:6px;padding:8px 14px;margin-bottom:7px;margin-left:12px">
        <div style="display:flex;align-items:center;gap:8px;margin-bottom:4px">
          <span style="color:${nameCol};font-weight:bold;font-size:0.85em">${escHtml(entry.fromName)}</span>
          <span style="background:#b7791f;color:#fff;padding:1px 6px;border-radius:4px;font-size:0.7em;letter-spacing:1px">💬 ASIDE</span>
        </div>
        <div style="color:#f6e05e;font-style:italic;font-size:0.86em;line-height:1.5">${escHtml(entry.publicMessage)}</div>
      </div>`;
      continue;
    }

    const phaseBg  = PHASE_COLORS[entry.phase] ?? '#4a5568';
    const badge    = PHASE_LABELS[entry.phase] ? `<span style="background:${phaseBg};color:#fff;padding:2px 7px;border-radius:4px;font-size:0.72em;letter-spacing:1px;white-space:nowrap">${PHASE_LABELS[entry.phase]}</span>` : '';
    const nameCol   = playerHexMap[entry.fromName] ?? '#9ab8d8';
    const borderCol = entry.fromId ? (playerHexMap[entry.fromName] ?? '#2d3748') : '#2d3748';

    const publicHtml = entry.publicMessage
      ? `<div style="color:#e2e8f0;line-height:1.55;font-size:0.88em">${escHtml(entry.publicMessage)}</div>`
      : '';
    const reasoningHtml = entry.reasoning
      ? `<div style="color:#7a9bb5;font-style:italic;font-size:0.8em;margin-top:5px;line-height:1.45;border-top:1px solid rgba(255,255,255,0.06);padding-top:5px"><em>💭 ${escHtml(entry.reasoning)}</em></div>`
      : '';
    html += `<div style="background:rgba(255,255,255,0.04);border:1px solid rgba(255,255,255,0.07);
      border-left:4px solid ${borderCol};border-radius:6px;padding:10px 14px;margin-bottom:7px">
      <div style="display:flex;align-items:center;gap:8px;margin-bottom:5px">
        <span style="color:${nameCol};font-weight:bold;font-size:0.9em">${escHtml(entry.fromName)}</span>
        ${badge}
      </div>
      ${publicHtml}${reasoningHtml}
    </div>`;
  }

  const scoreboard = [...scores].sort((a, b) => b.vp - a.vp).map(p => {
    const col = p.colorHex;
    return `<div style="display:flex;align-items:center;gap:8px;margin:3px 0"><div style="width:10px;height:10px;border-radius:50%;background:${col}"></div><b>${escHtml(p.name)}</b><span style="color:#f5d78e;margin-left:4px">${p.vp} VP</span></div>`;
  }).join('');

  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>AI Catan — Turn ${turnNum} Dialogue (Seed ${seed})</title>
<style>*{box-sizing:border-box;margin:0;padding:0}body{background:#0d2b4a;font-family:'Georgia',serif;color:#f0e6d3;display:flex;flex-direction:column;align-items:center;min-height:100vh}
header{padding:18px 0 4px;font-size:1.4em;letter-spacing:4px;color:#f5d78e;text-transform:uppercase}
#sub{font-size:0.75em;color:#9ab8d8;letter-spacing:2px;margin-bottom:16px}
#wrap{width:100%;max-width:740px;padding:0 18px}
#final{background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:8px;padding:12px 16px;margin:20px 0 32px}</style></head>
<body><header>AI CATAN</header>
<div id="sub">TURN ${turnNum} DIALOGUE — SEED: ${seed}</div>
<div id="wrap">
${html}
<div id="final"><div style="font-size:0.78em;letter-spacing:2px;color:#9ab8d8;margin-bottom:8px">SCORES AFTER TURN ${turnNum}</div>${scoreboard}</div>
</div></body></html>`;
}

function escHtml(s: string): string {
  return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}
